#Tomcat server port number = 8080, context-path = /
server:
  port: 8761

spring:
  application:
    name: SERVICE-REGISTRY

# Disable as Client
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

#logging.level.org.springframework.orm.hibernate5=DEBUG
logging:
  file:
    name: "logs/app.log"
    path: "."
  pattern:
    level: "[%-5level] %logger{36}.%M.[%line]"
    dateformat: "yyyy-MM-dd HH:mm:ss"
    correlation: "[%X{reqId}] - "

